### ISSUE TITLE
LevelUp event

### ISSUE THREAD

**Issue by NotSoMik** [Abadima/simply-xp-test#1] opened 2022-07-23 07:43 UTC
Can you give a better example about the level up event since there is the same example on the documentation and Im not sure what to do

**Comment by Abadima** [comment] 2022-07-23 09:13
Hello! As shown in my `index.js` file, I have enlisted 
```js
client.on('levelUp', async (message, data, role) => { your_code_here })
``` 
this is basically just a callback function, whenever the user levels up, as long as you have that code somewhere, it will trigger the event, allowing you to proceed however you wish!

If I was able to help, you may close the issue, otherwise please let me know how I should explain :)

**Comment by NotSoMik** [comment] 2022-07-23 10:16
Thanks for this info so something like

```js
const xp = require("simply-xp");
const client = require("..");

client.on("levelUp", async (message, data) => {
    message.channel.send({
        content: `🥳 <@${data.userID}>, **Level Up! 🎉** Now you are **level ${data.level}** in **${message.guild.name}**.`
    });
// if the user levels up gets a role, right?
    xp.lvlRole(message, data.userID, data.guildID);
    return;
})
will be fine?

**Comment by Abadima** [comment] 2022-07-23 15:24
Yep! That should work

**Comment by NotSoMik** [comment] 2022-07-23 16:56
Ok cool, if the user gets the role how can i add an extra message? Like the normale message will be 
```js
🥳 <@${data.userID}>, **Level Up! 🎉** Now you are **level ${data.level}** in **${message.guild.name}**.`
    });

and if the user get a role after it reaches a certain level the bot should add a text like: You got this role etc

**Comment by Abadima** [comment] 2022-07-23 18:02
It's possible! `role` is listed in the callback when the user levels up (using addXP method)

So you can just do something like this: 
```js
client.on("levelUp", async (message, data, role) => {
   // level up message goes here
   
   if (role != undefined) {
     <Channel>.send(`Hey! You have also received the following roles: ${<@&role.role>}`)
     <xp>.lvlRole(message, data.userID, data.guildID)
})
```
Which allows you to check if there are roles for the new level

TIP: `role` returns something along the lines of: `{ lvl: 5, role: "role-id" }`

**Comment by NotSoMik** [comment] 2022-07-23 18:22
That's amazing, ty for your help. I'll open this issue when I'll have other questions :)

**Comment by NotSoMik** [comment] 2022-07-24 07:05
yo I got another question lol, if i use all the functions of simply-xp what intent should I put? Only guild and guild messages?

**Comment by Abadima** [comment] 2022-07-24 13:47
For my test bot, I've only used the `Guild` intent for all functions!

It really depends on how you're using them. If it works, then you should be alright

**Comment by NotSoMik** [comment] 2022-07-24 14:12
Ok cool but is there a way we can customize this 
```js
if (!user) throw new Error('[XP] NO_DATA | User has no XP data.')
```
Because as you know if a user has no xp it will throw that error, so how can we avoid that

**Comment by Abadima** [comment] 2022-07-24 14:41
There isn't a way to change it @ core, HOWEVER! You can actually avoid this by using `<xp>.fetch()`, if the user is found, then use the rank function

If the user is NOT found, then you can use `<xp>.create(client, userid, guildid)` & then run `rank()`, that way you completely avoid that error

**Comment by NotSoMik** [comment] 2022-07-24 16:58
Nice, when I'll be free I'll send ex example and you can tell me if its correct

**Comment by NotSoMik** [comment] 2022-08-09 10:23
If I want to get more xp on Saturday and normal xp on the other days, something like this willl be fine, right?
```js
const date = new Date();
if (date.getDay() === 6)
            xp.addXP(message, message.author.id, message.guild.id, {
                min: 20,
                max: 35,
            });
        else
            xp.addXP(message, message.author.id, message.guild.id, {
                min: 1,
                max: 15,
            });
// I'm using this in my messageCreate event so I need the guild messages intent
```

also how can I get in the console the amount of xp that an user gets

**Comment by Abadima** [comment] 2022-08-09 22:22
Good day! Thank you for your patience; the code you gave should function as intended. Regarding the XP logging, you can see that it does so at [Our Guide](https://simplyxp.js.org/docs/addXP#returns-object.)!, so you'll just need to return it, something like: 
```js
xp.addXP(message, userid, guildid, { .. }).then(res => { console.log(res) })
// or you can also do this
var res = await xp.addXP(message, userid, guildid, { ... })
console.log(res)
```
Both of them should return something like `{ xp: 15 }`

**Comment by NotSoMik** [comment] 2022-08-09 22:50
Oh thanks a lot

**Comment by NotSoMik** [comment] 2022-08-09 22:52
Since there is a rank card will you ever make a leaderboard card where are displayed the top 10 people

**Comment by Abadima** [comment] 2022-08-09 23:09
Although we do not currently have a leaderboard card, that is an interesting thought! I'll add it to my to-do list; I might introduce it in v2! In the meantime, you can still set a limit of 10 people by following the steps on [Our Documentation](https://simplyxp.js.org/docs/leaderboard#usage) if you haven't already known :D

**Comment by NotSoMik** [comment] 2022-08-09 23:13
yea I know how to make it but it will be cool if you add that :)

**Comment by NotSoMik** [comment] 2022-08-16 10:29
> It's possible! `role` is listed in the callback when the user levels up (using addXP method)
> 
> So you can just do something like this:
> 
> ```js
> client.on("levelUp", async (message, data, role) => {
>    // level up message goes here
>    
>    if (role != undefined) {
>      <Channel>.send(`Hey! You have also received the following roles: ${<@&role.role>}`)
>      <xp>.lvlRole(message, data.userID, data.guildID)
> })
> ```
> 
> Which allows you to check if there are roles for the new level
> 
> TIP: `role` returns something along the lines of: `{ lvl: 5, role: "role-id" }`

Hello again! About that, if I set more roles at the same level, the bot adds them but sends a message saying that it has only added one role, how can I fix that :)

**Comment by Abadima** [comment] 2022-08-16 20:24
Hey there! Can you provide some logs, and the message it's saying? I'll look further into this matter.

**Comment by NotSoMik** [comment] 2022-08-16 21:30
Sure, hope its clear
![Screenshot_20220816-233025_Discord](https://user-images.githubusercontent.com/74645196/184988736-9c3a5880-a318-4013-a464-227c3a95a70a.jpg)

**Comment by NotSoMik** [comment] 2022-08-16 21:31
I got both roles tho

**Comment by Abadima** [comment] 2022-08-17 12:27
Assuming you're fetching the role(s) from the levelUp event, I might be able to crack down the issue, please hold! I'll reply as soon as possible.

**Comment by NotSoMik** [comment] 2022-08-17 12:45
Sure, take your time

**Comment by Abadima** [comment] 2022-08-17 12:47
Hey There! I've identified the bug and fixed it:
I just need to make sure that all of the other fixes are working properly before I release the next update.

**Comment by NotSoMik** [comment] 2022-08-17 12:55
Good job, so that was a bug, right?

**Comment by Abadima** [comment] 2022-08-17 13:04
Yeah! A minor mistake was made in earlier versions of the package.

**Comment by NotSoMik** [comment] 2022-08-17 13:12
Oh ok, feel free to close this issue

**Comment by Abadima** [comment] 2022-08-17 13:21
Hello once more! Simply-XP has just been updated to `v1.3.4`, which includes all the most recent updates and a few more minor changes that I think you'll like.

**Closed as completed by Abadima** 2022-08-17 13:21 UTC
Labels: documentation, question

**Comment by NotSoMik** [comment] 2022-08-17 14:12
Hello I got another issue 
![Screenshot_20220817-161016_Discord](https://user-images.githubusercontent.com/74645196/185156078-bf5410c7-c2ae-41ba-81dc-a6a333afb3c6.jpg)

```js
if (role != undefined) {
            message.channel.send({
                content: `Hey! You have also received the following roles: <@&${role.role}>`,
            });
            xp.lvlRole(message, data.userID, data.guildID);
        }

**Comment by NotSoMik** [comment] 2022-08-17 14:12
With the new version @Abadima

**Comment by Abadima** [comment] 2026-03-15 01:43
Hello there! I hadn't received a notification for this whoops,

Pardon the minor delay, are you still having this issue in v1.3.8?
